#!/usr/bin/env python3
"""
Visualize how a teacher model's per-token entropy changes across the length of
sequences generated by different models.

Multi-GPU version:
  - Generation: vLLM handles all prompts in one batch (vLLM does its own
    GPU scheduling, no need for manual multi-GPU).
  - Entropy: 8 GPUs in parallel, each evaluating one sample via a subprocess
    that sets CUDA_VISIBLE_DEVICES *before* importing torch.

Pipeline (mirrors infer.py):
  1. Load math problems from the dataset (one per GPU).
  2. Apply the environment-specific prompt (MATH_TEMPLATE).
  3. Generate all responses with a *generator* model via vLLM (batched).
  4. Compute the teacher model's per-position entropy in parallel (1 GPU per sample).
  5. Average entropy across samples and plot.

Two stages:
  Stage A - generator = Math Teacher  (OpenThinker3-7B)
  Stage B - generator = Student       (qwen-2.5-7b-it)
In both stages the *evaluator* is always the Math Teacher.
"""

import os
import sys
import argparse
import json
import subprocess
import tempfile
import pickle
from pathlib import Path
from typing import List, Dict, Tuple
import random

import numpy as np
import datasets
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from agent_system.environments.prompts.math import MATH_TEMPLATE

# ---------------------------------------------------------------------------
# Defaults (matching run_opd_multitask_qwen2.5-7b_it.sh)
# ---------------------------------------------------------------------------
MATH_TEACHER = "/data/home/zdhs0010/agentic/model/OpenThinker3-7B"
STUDENT_MODEL1 = "/data/home/zdhs0010/agentic/model/qwen-2.5-7b-it"
STUDENT_MODEL2 = "/data/home/zdhs0010/agentic/verl-agent-multi/ckpts/math_original_opd_lr2e-6_0219_192951/global_step_80/actor_merged"
DATA_PATH = "/data/home/zdhs0010/agentic/verl-agent-multi/data/math_opd/train.parquet"
MAX_NEW_TOKENS = 16384
NUM_GPUS = 8

NAME = {
    "teacher": "OpenThinker3-7B",
    "student": "Qwen2.5-7B-It",
    "student2": "Qwen2.5-7B-It(opd-step80)",
}


# ---------------------------------------------------------------------------
# 1. Build the chat prompt – same pipeline as infer.py
# ---------------------------------------------------------------------------
def build_prompt(tokenizer, raw_question: str) -> str:
    env_prompt = MATH_TEMPLATE.format(task_description=raw_question)
    messages = [
        {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."},
        {"role": "user", "content": env_prompt},
    ]
    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)


# ---------------------------------------------------------------------------
# 2. Generate with vLLM – single process, batched, vLLM handles GPUs
# ---------------------------------------------------------------------------
def generate_with_vllm(
    model_path: str,
    prompts: List[str],
    max_new_tokens: int = MAX_NEW_TOKENS,
    temperature: float = 1.0,
    top_p: float = 0.9,
    gpu_memory_utilization: float = 0.85,
    tensor_parallel_size: int = 1,
) -> List[str]:
    from vllm import LLM, SamplingParams
    import torch

    llm = LLM(
        model=model_path,
        trust_remote_code=True,
        dtype="bfloat16",
        gpu_memory_utilization=gpu_memory_utilization,
        tensor_parallel_size=tensor_parallel_size,
        max_model_len=2048 + max_new_tokens,
    )
    params = SamplingParams(
        max_tokens=max_new_tokens,
        temperature=temperature,
        top_p=top_p,
    )
    outputs = llm.generate(prompts, params)
    results = [out.outputs[0].text for out in outputs]

    del llm
    torch.cuda.empty_cache()
    return results


# ---------------------------------------------------------------------------
# 3. Entropy computation – runs in a *separate subprocess* per GPU
#    This is the script that each subprocess executes.
# ---------------------------------------------------------------------------
ENTROPY_WORKER_SCRIPT = r'''
import os
import sys
import pickle

gpu_id = sys.argv[1]
input_path = sys.argv[2]
output_path = sys.argv[3]

os.environ["CUDA_VISIBLE_DEVICES"] = gpu_id

import torch
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM

with open(input_path, "rb") as f:
    task = pickle.load(f)

teacher_path = task["teacher_path"]
full_text = task["full_text"]
prompt_len = task["prompt_len"]
batch_chunk = task.get("batch_chunk", 2048)

device = "cuda:0"

tokenizer = AutoTokenizer.from_pretrained(teacher_path, trust_remote_code=True, padding_side="left")
model = AutoModelForCausalLM.from_pretrained(
    teacher_path,
    trust_remote_code=True,
    torch_dtype=torch.bfloat16,
    device_map={"": device},
)
model.eval()

input_ids = tokenizer.encode(full_text, return_tensors="pt", add_special_tokens=False).to(device)
seq_len = input_ids.shape[1]

all_entropies = []

if prompt_len < seq_len:
    with torch.no_grad():
        for start in range(0, seq_len - 1, batch_chunk):
            end = min(start + batch_chunk, seq_len - 1)
            chunk_ids = input_ids[:, start : end + 1]
            logits = model(chunk_ids).logits
            log_probs = torch.log_softmax(logits[:, :-1, :], dim=-1)
            probs = log_probs.exp()
            entropy = -(probs * log_probs).sum(dim=-1).squeeze(0)
            for i, ent_val in enumerate(entropy.float().cpu().tolist()):
                pred_pos = start + i + 1
                if pred_pos >= prompt_len:
                    all_entropies.append(ent_val)

result = {"entropies": np.array(all_entropies), "success": True}
with open(output_path, "wb") as f:
    pickle.dump(result, f)
'''


def compute_entropy_parallel(
    teacher_path: str,
    samples: List[Dict],
    num_gpus: int = NUM_GPUS,
) -> List[Dict]:
    """
    Launch one subprocess per GPU. Each subprocess:
      - sets CUDA_VISIBLE_DEVICES *before* importing torch
      - loads the teacher model on cuda:0 (the single visible GPU)
      - computes response-only entropy
      - writes result to a pickle file
    """
    # Write the worker script to a temp file
    script_dir = tempfile.mkdtemp(prefix="entropy_workers_")
    script_path = os.path.join(script_dir, "entropy_worker.py")
    with open(script_path, "w") as f:
        f.write(ENTROPY_WORKER_SCRIPT)
    
    # Prepare input/output files and launch subprocesses
    procs = []
    io_paths = []
    
    for i, sample in enumerate(samples[:num_gpus]):
        gpu_id = str(i)
        input_path = os.path.join(script_dir, f"input_{i}.pkl")
        output_path = os.path.join(script_dir, f"output_{i}.pkl")
        
        task = {
            "teacher_path": teacher_path,
            "full_text": sample["full_text"],
            "prompt_len": sample["prompt_len"],
        }
        with open(input_path, "wb") as f:
            pickle.dump(task, f)
        
        proc = subprocess.Popen(
            [sys.executable, script_path, gpu_id, input_path, output_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        procs.append(proc)
        io_paths.append((input_path, output_path, i))
        print(f"  [GPU {gpu_id}] Launched entropy worker for problem {sample['problem_idx']}")
    
    # Collect results
    results = []
    for proc, (input_path, output_path, idx) in zip(procs, io_paths):
        stdout, stderr = proc.communicate()
        sample = samples[idx]
        
        if proc.returncode != 0:
            print(f"  [GPU {idx}] FAILED (exit code {proc.returncode})")
            if stderr:
                print(f"    stderr: {stderr.decode()[-500:]}")
            results.append({
                "problem_idx": sample["problem_idx"],
                "entropies": np.array([]),
                "response_len": sample["response_len"],
                "success": False,
            })
            continue
        
        try:
            with open(output_path, "rb") as f:
                result = pickle.load(f)
            results.append({
                "problem_idx": sample["problem_idx"],
                "entropies": result["entropies"],
                "response_len": sample["response_len"],
                "success": result["success"],
            })
            print(f"  [GPU {idx}] Done. Entropy length: {len(result['entropies'])}")
        except Exception as e:
            print(f"  [GPU {idx}] Failed to read result: {e}")
            results.append({
                "problem_idx": sample["problem_idx"],
                "entropies": np.array([]),
                "response_len": sample["response_len"],
                "success": False,
            })
    
    # Cleanup temp files
    import shutil
    shutil.rmtree(script_dir, ignore_errors=True)
    
    return results


# ---------------------------------------------------------------------------
# 4. Run a full stage: generate + entropy
# ---------------------------------------------------------------------------
def run_stage_multi_gpu(
    stage_name: str,
    generator_path: str,
    teacher_path: str,
    dataset,
    problem_indices: List[int],
    max_new_tokens: int,
    gpu_memory_utilization: float,
    num_gpus: int = NUM_GPUS,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Dict]:
    from transformers import AutoTokenizer

    print(f"\n{'='*72}")
    print(f"  Stage: {stage_name}")
    print(f"  Generator : {generator_path}")
    print(f"  Evaluator : {teacher_path}")
    print(f"  Problems  : {problem_indices}")
    print(f"  GPUs      : {num_gpus}")
    print(f"{'='*72}")

    # Build prompts
    tokenizer = AutoTokenizer.from_pretrained(generator_path, trust_remote_code=True, padding_side="left")
    teacher_tokenizer = AutoTokenizer.from_pretrained(teacher_path, trust_remote_code=True, padding_side="left")

    prompts = []
    raw_questions = []
    for idx in problem_indices:
        example = dataset[idx]
        raw_q = example["prompt"][0]["content"]
        raw_questions.append(raw_q)
        prompts.append(build_prompt(tokenizer, raw_q))

    # --- Step 1: Generate all responses in one vLLM batch ---
    print("\n[1/2] Generating responses with vLLM (batched) …")
    responses = generate_with_vllm(
        model_path=generator_path,
        prompts=prompts,
        max_new_tokens=max_new_tokens,
        gpu_memory_utilization=gpu_memory_utilization,
    )

    # Prepare samples for entropy computation
    # Re-encode with teacher tokenizer since entropy is computed by teacher
    samples = []
    for i, (idx, prompt_text, response_text) in enumerate(zip(problem_indices, prompts, responses)):
        full_text = prompt_text + response_text
        teacher_prompt = build_prompt(teacher_tokenizer, raw_questions[i])
        teacher_full = teacher_prompt + response_text
        prompt_ids = teacher_tokenizer.encode(teacher_prompt, add_special_tokens=False)
        full_ids = teacher_tokenizer.encode(teacher_full, add_special_tokens=False)
        prompt_len = len(prompt_ids)
        total_len = len(full_ids)
        response_len = total_len - prompt_len
        
        print(f"  Problem {idx}: prompt={prompt_len}, response={response_len}, total={total_len}")
        
        samples.append({
            "problem_idx": idx,
            "full_text": teacher_full,
            "prompt_len": prompt_len,
            "response_len": response_len,
            "total_len": total_len,
        })

    # --- Step 2: Compute entropy in parallel ---
    print(f"\n[2/2] Computing entropy in parallel ({num_gpus} GPUs) …")
    results = compute_entropy_parallel(
        teacher_path=teacher_path,
        samples=samples,
        num_gpus=num_gpus,
    )

    # Filter successful results
    valid_results = [r for r in results if r["success"] and len(r["entropies"]) > 0]
    print(f"\n  Valid results: {len(valid_results)} / {len(results)}")

    if len(valid_results) == 0:
        empty = np.array([])
        return empty, empty, empty, {"valid_count": 0, "problem_indices": [], "response_lens": [], "max_len": 0, "avg_entropy_mean": 0.0}

    # Average entropy across samples (pad shorter sequences with NaN, then nanmean)
    max_len = max(len(r["entropies"]) for r in valid_results)
    entropy_matrix = np.full((len(valid_results), max_len), np.nan)

    for i, r in enumerate(valid_results):
        ent = r["entropies"]
        entropy_matrix[i, :len(ent)] = ent

    avg_entropies = np.nanmean(entropy_matrix, axis=0)
    std_entropies = np.nanstd(entropy_matrix, axis=0)
    valid_counts = np.sum(~np.isnan(entropy_matrix), axis=0)

    metadata = {
        "valid_count": len(valid_results),
        "problem_indices": [r["problem_idx"] for r in valid_results],
        "response_lens": [r["response_len"] for r in valid_results],
        "max_len": max_len,
        "avg_entropy_mean": float(np.nanmean(avg_entropies)),
        "avg_entropy_std": float(np.nanstd(avg_entropies)),
    }

    return avg_entropies, std_entropies, valid_counts, metadata


# ---------------------------------------------------------------------------
# 5. Plotting
# ---------------------------------------------------------------------------
def plot_entropy_averaged(
    entropies: np.ndarray,
    std_entropies: np.ndarray,
    valid_counts: np.ndarray,
    title: str,
    save_path: str,
    window: int = 64,
    show_std: bool = True,
    min_samples: int = 2,
):
    """Plot averaged entropy for response tokens."""
    mask = valid_counts >= min_samples
    n_valid = np.sum(mask)

    if n_valid == 0:
        print(f"  No valid positions to plot, skipping {save_path}")
        return

    positions = np.arange(len(entropies))

    if len(entropies) > window:
        kernel = np.ones(window) / window
        smoothed = np.convolve(entropies, kernel, mode="same")
        smoothed_std = np.convolve(std_entropies, kernel, mode="same")
    else:
        smoothed = entropies
        smoothed_std = std_entropies

    fig, ax = plt.subplots(figsize=(16, 5))

    if show_std:
        ax.fill_between(positions, smoothed - smoothed_std, smoothed + smoothed_std,
                        alpha=0.2, color="steelblue", label="±1 std")

    ax.plot(positions, smoothed, linewidth=1.2, color="steelblue", label=f"mean (smoothed w={window})")

    ax.set_xlabel("Response token position")
    ax.set_ylabel("Entropy")
    ax.set_title(title)
    ax.legend(loc="upper right", fontsize=8)
    ax.set_xlim(0, len(entropies))
    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)
    print(f"  Saved plot -> {save_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Teacher entropy vs. sequence position (multi-GPU)")
    parser.add_argument("--teacher", default=MATH_TEACHER, help="Path to math teacher model")
    parser.add_argument("--student", default=STUDENT_MODEL1, help="Path to student model")
    parser.add_argument("--student2", default=STUDENT_MODEL2, help="Path to student model 2")
    parser.add_argument("--data", default=DATA_PATH, help="Path to math test parquet")
    parser.add_argument("--num_samples", type=int, default=8, help="Number of samples (one per GPU)")
    parser.add_argument("--start_idx", type=int, default=0, help="Starting problem index")
    parser.add_argument("--random_sample", action="store_true", help="Randomly sample problems")
    parser.add_argument("--max_new_tokens", type=int, default=MAX_NEW_TOKENS)
    parser.add_argument("--out_dir", default="analyze/outputs", help="Directory for plots and data")
    parser.add_argument("--gpu_mem", type=float, default=0.85, help="vLLM GPU memory utilization")
    parser.add_argument("--num_gpus", type=int, default=NUM_GPUS, help="Number of GPUs to use")
    parser.add_argument("--stages", nargs="+", default=["teacher", "student", "student2"],
                        choices=["teacher", "student", "student2"],
                        help="Which stages to run")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for sampling")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Loading dataset …")
    ds = datasets.load_dataset("parquet", data_files=args.data, split="train")
    print(f"Dataset size: {len(ds)}")

    if args.random_sample:
        random.seed(args.seed)
        problem_indices = random.sample(range(len(ds)), min(args.num_samples, len(ds)))
    else:
        problem_indices = list(range(args.start_idx, min(args.start_idx + args.num_samples, len(ds))))

    print(f"Selected problems: {problem_indices}")

    all_results = {}

    # --- Stage A: Teacher generates, teacher evaluates ---
    if "teacher" in args.stages:
        avg_ent, std_ent, valid_counts, meta = run_stage_multi_gpu(
            stage_name=NAME["teacher"],
            generator_path=args.teacher,
            teacher_path=args.teacher,
            dataset=ds,
            problem_indices=problem_indices,
            max_new_tokens=args.max_new_tokens,
            gpu_memory_utilization=args.gpu_mem,
            num_gpus=args.num_gpus,
        )
        all_results["teacher"] = (avg_ent, std_ent, valid_counts, meta)

        if meta["valid_count"] > 0:
            plot_path = out_dir / f"entropy_teacher_avg_n{meta['valid_count']}.png"
            plot_entropy_averaged(
                avg_ent, std_ent, valid_counts,
                title=f"Teacher Entropy - {NAME['teacher']} (n={meta['valid_count']})",
                save_path=str(plot_path),
            )

    # --- Stage B: Student generates, teacher evaluates ---
    if "student" in args.stages:
        avg_ent, std_ent, valid_counts, meta = run_stage_multi_gpu(
            stage_name=NAME["student"],
            generator_path=args.student,
            teacher_path=args.teacher,
            dataset=ds,
            problem_indices=problem_indices,
            max_new_tokens=args.max_new_tokens,
            gpu_memory_utilization=args.gpu_mem,
            num_gpus=args.num_gpus,
        )
        all_results["student"] = (avg_ent, std_ent, valid_counts, meta)

        if meta["valid_count"] > 0:
            plot_path = out_dir / f"entropy_student_avg_n{meta['valid_count']}.png"
            plot_entropy_averaged(
                avg_ent, std_ent, valid_counts,
                title=f"Teacher Entropy - {NAME['student']} (n={meta['valid_count']})",
                save_path=str(plot_path),
            )

    # --- Stage C: Student2 generates, teacher evaluates ---
    if "student2" in args.stages:
        avg_ent, std_ent, valid_counts, meta = run_stage_multi_gpu(
            stage_name=NAME["student2"],
            generator_path=args.student2,
            teacher_path=args.teacher,
            dataset=ds,
            problem_indices=problem_indices,
            max_new_tokens=args.max_new_tokens,
            gpu_memory_utilization=args.gpu_mem,
            num_gpus=args.num_gpus,
        )
        all_results["student2"] = (avg_ent, std_ent, valid_counts, meta)

        if meta["valid_count"] > 0:
            plot_path = out_dir / f"entropy_student2_avg_n{meta['valid_count']}.png"
            plot_entropy_averaged(
                avg_ent, std_ent, valid_counts,
                title=f"Teacher Entropy - {NAME['student2']} (n={meta['valid_count']})",
                save_path=str(plot_path),
            )

    # --- Combined comparison plot ---
    valid_results = {k: v for k, v in all_results.items() if v[3]["valid_count"] > 0}
    if len(valid_results) >= 2:
        print("\nGenerating combined comparison plot …")
        fig, ax = plt.subplots(figsize=(16, 6))
        window = 64
        kernel = np.ones(window) / window
        palette = {"teacher": "red", "student": "green", "student2": "blue"}

        max_len = 0
        for label, (avg_ent, std_ent, valid_counts, meta) in valid_results.items():
            n = len(avg_ent)
            if n == 0:
                continue
            max_len = max(max_len, n)
            positions = np.arange(n)
            smoothed = np.convolve(avg_ent, kernel, mode="same") if n > window else avg_ent
            smoothed_std = np.convolve(std_ent, kernel, mode="same") if n > window else std_ent

            ax.fill_between(positions, smoothed - smoothed_std, smoothed + smoothed_std,
                            alpha=0.15, color=palette[label])
            ax.plot(positions, smoothed, linewidth=1.2, color=palette[label],
                    label=f"{NAME[label]} (mean={np.nanmean(avg_ent):.2f})")

        ax.set_xlabel("Position in Generated Response", fontweight="bold")
        ax.set_ylabel("Teacher Entropy", fontweight="bold")
        # ax.set_title(f"Teacher Entropy Compariso", fontweight="bold")
        ax.legend(loc="upper right", fontsize=8)
        ax.set_xlim(0, max_len)
        ax.grid(True)
        fig.tight_layout()

        cmp_path_png = out_dir / f"entropy_comparison_avg_n{args.num_samples}.png"
        cmp_path_pdf = out_dir / f"entropy_comparison_avg_n{args.num_samples}.pdf"
        fig.savefig(str(cmp_path_png), dpi=150)
        fig.savefig(str(cmp_path_pdf), dpi=150)
        plt.close(fig)
        print(f"  Saved comparison -> {cmp_path_png}")

    # Save metadata
    meta_path = out_dir / f"entropy_metadata_n{args.num_samples}.json"
    meta_to_save = {
        label: {
            "valid_count": meta["valid_count"],
            "problem_indices": meta["problem_indices"],
            "response_lens": meta["response_lens"],
            "max_len": meta["max_len"],
            "avg_entropy_mean": meta["avg_entropy_mean"],
        }
        for label, (_, _, _, meta) in all_results.items()
    }
    with open(meta_path, "w") as f:
        json.dump(meta_to_save, f, indent=2)
    print(f"  Saved metadata -> {meta_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
