#!/usr/bin/env python3
"""
Visualize how a teacher model's per-token entropy changes across the length of
sequences generated by different models.

Pipeline (mirrors infer.py):
  1. Load a math problem from the dataset.
  2. Apply the environment-specific prompt (MATH_TEMPLATE).
  3. Generate a response with a *generator* model via vLLM.
  4. Compute the teacher model's per-position entropy over the full
     (prompt + response) sequence using HuggingFace for exact logits.
  5. Plot entropy vs. position with milestone markers (4k, 8k, 12k, 16k).

Two stages:
  Stage A - generator = Math Teacher  (OpenThinker3-7B)
  Stage B - generator = Student       (qwen-2.5-7b-it)
In both stages the *evaluator* is always the Math Teacher.
"""

import os
import sys
import argparse
import json
import math
from pathlib import Path
from typing import List, Dict, Any, Optional

import torch
import numpy as np
import datasets
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForCausalLM

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from agent_system.environments.prompts.math import MATH_TEMPLATE

# ---------------------------------------------------------------------------
# Defaults (matching run_opd_multitask_qwen2.5-7b_it.sh)
# ---------------------------------------------------------------------------
MATH_TEACHER = "/data/home/zdhs0010/agentic/model/OpenThinker3-7B"
STUDENT_MODEL1 = "/data/home/zdhs0010/agentic/model/qwen-2.5-7b-it"
STUDENT_MODEL2 = "/data/home/zdhs0010/agentic/verl-agent-multi/ckpts/math_original_opd_lr2e-6_0219_192951/global_step_80/actor_merged"
DATA_PATH = "/data/home/zdhs0010/agentic/verl-agent-multi/data/math_opd/train.parquet"
MAX_NEW_TOKENS = 16384
MILESTONES = [4096, 8192, 12288, 16384]
MILESTONE_LABELS = ["4k", "8k", "12k", "16k"]
NAME = {
    "teacher": "OpenThinker3-7B",
    "student": "Qwen2.5-7B-It",
    "student2": "Qwen2.5-7B-It(opd-step80)",
}


# ---------------------------------------------------------------------------
# 1. Build the chat prompt – same pipeline as infer.py
# ---------------------------------------------------------------------------
def build_prompt(tokenizer: AutoTokenizer, raw_question: str) -> str:
    env_prompt = MATH_TEMPLATE.format(task_description=raw_question)
    messages = [
        {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."},
        {"role": "user", "content": env_prompt},
    ]
    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)


# ---------------------------------------------------------------------------
# 2. Generate with vLLM (fast, batched)
# ---------------------------------------------------------------------------
def generate_with_vllm(
    model_path: str,
    prompts: List[str],
    max_new_tokens: int = MAX_NEW_TOKENS,
    temperature: float = 1.0,
    top_p: float = 0.9,
    gpu_memory_utilization: float = 0.85,
    tensor_parallel_size: int = 1,
) -> List[str]:
    from vllm import LLM, SamplingParams

    llm = LLM(
        model=model_path,
        trust_remote_code=True,
        dtype="bfloat16",
        gpu_memory_utilization=gpu_memory_utilization,
        tensor_parallel_size=tensor_parallel_size,
        max_model_len=2048 + max_new_tokens,
    )
    params = SamplingParams(
        max_tokens=max_new_tokens,
        temperature=temperature,
        top_p=top_p,
    )
    outputs = llm.generate(prompts, params)
    results = [out.outputs[0].text for out in outputs]

    del llm
    torch.cuda.empty_cache()
    return results


# ---------------------------------------------------------------------------
# 3. Compute per-token entropy under the teacher model (HF, exact logits)
#    Only computes entropy for the RESPONSE part (excludes prompt).
# ---------------------------------------------------------------------------
@torch.no_grad()
def compute_response_entropy(
    model: AutoModelForCausalLM,
    tokenizer: AutoTokenizer,
    full_text: str,
    prompt_len: int,
    batch_chunk: int = 2048,
) -> np.ndarray:
    """
    Return per-position entropy (nats) for response tokens only.
    
    Args:
        model: The teacher model for computing logits
        tokenizer: Tokenizer
        full_text: prompt + response concatenated
        prompt_len: Number of tokens in the prompt (entropy starts after this)
        batch_chunk: Chunk size for processing long sequences
    
    Returns:
        Entropy array of length (total_len - prompt_len), one value per response token.
    """
    input_ids = tokenizer.encode(full_text, return_tensors="pt", add_special_tokens=False).to(model.device)
    seq_len = input_ids.shape[1]
    
    if prompt_len >= seq_len:
        return np.array([])
    
    all_entropies: List[float] = []
    
    # We need context from the prompt to predict the first response token.
    # Process in chunks, but only collect entropy for positions >= prompt_len.
    for start in range(0, seq_len - 1, batch_chunk):
        end = min(start + batch_chunk, seq_len - 1)
        chunk_ids = input_ids[:, start : end + 1]

        logits = model(chunk_ids).logits  # (1, chunk_len, vocab)
        # logits[:, t, :] predicts token at position (start + t + 1)
        log_probs = torch.log_softmax(logits[:, :-1, :], dim=-1)  # (1, chunk_len-1, vocab)
        probs = log_probs.exp()
        entropy = -(probs * log_probs).sum(dim=-1).squeeze(0)  # (chunk_len-1,)
        
        # Only keep entropy for response positions
        for i, ent_val in enumerate(entropy.float().cpu().tolist()):
            pred_pos = start + i + 1  # position of the token being predicted
            if pred_pos >= prompt_len:
                all_entropies.append(ent_val)

    return np.array(all_entropies)


# ---------------------------------------------------------------------------
# 4. Plotting (response-only, x-axis starts at 0 = first response token)
# ---------------------------------------------------------------------------
def plot_entropy(
    entropies: np.ndarray,
    title: str,
    save_path: str,
    window: int = 64,
):
    """
    Plot entropy for response tokens only.
    X-axis: position within response (0 = first response token).
    """
    n = len(entropies)
    if n == 0:
        print(f"  No response tokens to plot, skipping {save_path}")
        return
    
    positions = np.arange(n)

    # Smoothed curve (moving average)
    if n > window:
        kernel = np.ones(window) / window
        smoothed = np.convolve(entropies, kernel, mode="same")
    else:
        smoothed = entropies

    fig, ax = plt.subplots(figsize=(16, 5))
    ax.fill_between(positions, entropies, alpha=0.15, color="steelblue", label="raw")
    ax.plot(positions, smoothed, linewidth=1.0, color="steelblue", label=f"smoothed (w={window})")


    ax.set_xlabel("Response token position")
    ax.set_ylabel("Entropy")
    ax.set_title(title)
    ax.legend(loc="upper right", fontsize=8)
    ax.set_xlim(0, n)
    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)
    print(f"  Saved plot -> {save_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def run_stage(
    stage_name: str,
    generator_path: str,
    teacher_path: str,
    prompt_text: str,
    tokenizer: AutoTokenizer,
    out_dir: Path,
    max_new_tokens: int,
    problem_idx: int,
    gpu_memory_utilization: float,
    tensor_parallel_size: int,
):
    print(f"\n{'='*72}")
    print(f"  Stage: {stage_name}")
    print(f"  Generator : {generator_path}")
    print(f"  Evaluator : {teacher_path}")
    print(f"{'='*72}")

    # --- generate ---
    print("\n[1/3] Generating response with vLLM …")
    responses = generate_with_vllm(
        model_path=generator_path,
        prompts=[prompt_text],
        max_new_tokens=max_new_tokens,
        gpu_memory_utilization=gpu_memory_utilization,
        tensor_parallel_size=tensor_parallel_size,
    )
    response_text = responses[0]
    full_text = prompt_text + response_text

    prompt_ids = tokenizer.encode(prompt_text, add_special_tokens=False)
    full_ids = tokenizer.encode(full_text, add_special_tokens=False)
    prompt_len = len(prompt_ids)
    total_len = len(full_ids)
    print(f"  Prompt tokens : {prompt_len}")
    print(f"  Response tokens: {total_len - prompt_len}")
    print(f"  Total tokens   : {total_len}")

    # --- load teacher for entropy ---
    print("\n[2/3] Loading teacher model for entropy computation …")
    teacher_model = AutoModelForCausalLM.from_pretrained(
        teacher_path,
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
        device_map="auto",
    )
    teacher_model.eval()

    print("  Computing per-token entropy (response only) …")
    entropies = compute_response_entropy(teacher_model, tokenizer, full_text, prompt_len)
    response_len = total_len - prompt_len
    print(f"  Response tokens: {response_len}")
    print(f"  Entropy array length: {len(entropies)}")

    del teacher_model
    torch.cuda.empty_cache()

    # --- plot ---
    print("\n[3/3] Plotting …")
    safe_name = stage_name.replace(" ", "_").lower()
    plot_path = out_dir / f"entropy_{safe_name}_prob{problem_idx}.png"
    plot_entropy(
        entropies,
        title=f"Teacher Entropy (response only) - {stage_name} (problem {problem_idx})",
        save_path=str(plot_path),
    )

    # --- save raw data ---
    json_path = out_dir / f"entropy_{safe_name}_prob{problem_idx}.json"
    payload = {
        "stage": stage_name,
        "generator": generator_path,
        "evaluator": teacher_path,
        "problem_idx": problem_idx,
        "prompt_len": prompt_len,
        "response_len": response_len,
        "total_len": total_len,
        "response_text_preview": response_text[:500],
        "entropy_mean": float(np.mean(entropies)) if len(entropies) > 0 else None,
        "entropy_std": float(np.std(entropies)) if len(entropies) > 0 else None,
    }
    with open(json_path, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"  Saved metadata -> {json_path}")

    return entropies, prompt_len, total_len


def main():
    parser = argparse.ArgumentParser(description="Teacher entropy vs. sequence position")
    parser.add_argument("--teacher", default=MATH_TEACHER, help="Path to math teacher model")
    parser.add_argument("--student", default=STUDENT_MODEL1, help="Path to student model")
    parser.add_argument("--student2", default=STUDENT_MODEL2, help="Path to student model")
    parser.add_argument("--data", default=DATA_PATH, help="Path to math test parquet")
    parser.add_argument("--problem_idx", type=int, default=0, help="Index of the problem to use")
    parser.add_argument("--max_new_tokens", type=int, default=MAX_NEW_TOKENS)
    parser.add_argument("--out_dir", default="analyze/outputs", help="Directory for plots and data")
    parser.add_argument("--gpu_mem", type=float, default=0.85, help="vLLM GPU memory utilization")
    parser.add_argument("--tp", type=int, default=1, help="Tensor parallel size for vLLM")
    parser.add_argument("--stages", nargs="+", default=["teacher", "student", "student2"],
                        choices=["teacher", "student", "student2"],
                        help="Which stages to run (default: both)")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Load dataset
    print("Loading dataset …")
    ds = datasets.load_dataset("parquet", data_files=args.data, split="train")
    example = ds[args.problem_idx]
    raw_question = example["prompt"][0]["content"]
    ground_truth = example["reward_model"]["ground_truth"]
    print(f"Problem {args.problem_idx}: {raw_question[:120]}…")
    print(f"Ground truth: {ground_truth}")

    # Tokenizer (shared across stages – both models use Qwen tokenizer family)
    tokenizer = AutoTokenizer.from_pretrained(args.teacher, trust_remote_code=True, padding_side="left")
    prompt_text = build_prompt(tokenizer, raw_question)

    all_entropies = {}

    # --- Stage A: Teacher generates, teacher evaluates ---
    if "teacher" in args.stages:
        ent, pl, tl = run_stage(
            stage_name=NAME["teacher"],
            generator_path=args.teacher,
            teacher_path=args.teacher,
            prompt_text=prompt_text,
            tokenizer=tokenizer,
            out_dir=out_dir,
            max_new_tokens=args.max_new_tokens,
            problem_idx=args.problem_idx,
            gpu_memory_utilization=args.gpu_mem,
            tensor_parallel_size=args.tp,
        )
        all_entropies["teacher"] = (ent, pl, tl)

    # --- Stage B: Student generates, teacher evaluates ---
    if "student" in args.stages:
        student_tokenizer = AutoTokenizer.from_pretrained(args.student, trust_remote_code=True, padding_side="left")
        student_prompt = build_prompt(student_tokenizer, raw_question)

        ent, pl, tl = run_stage(
            stage_name=NAME["student"],
            generator_path=args.student,
            teacher_path=args.teacher,
            prompt_text=student_prompt,
            tokenizer=tokenizer,
            out_dir=out_dir,
            max_new_tokens=args.max_new_tokens,
            problem_idx=args.problem_idx,
            gpu_memory_utilization=args.gpu_mem,
            tensor_parallel_size=args.tp,
        )
        all_entropies["student"] = (ent, pl, tl)
    
    if "student2" in args.stages:
        student2_tokenizer = AutoTokenizer.from_pretrained(args.student2, trust_remote_code=True, padding_side="left")
        student2_prompt = build_prompt(student2_tokenizer, raw_question)
        ent, pl, tl = run_stage(
            stage_name=NAME["student2"],
            generator_path=args.student2,
            teacher_path=args.teacher,
            prompt_text=student2_prompt,
            tokenizer=tokenizer,

            out_dir=out_dir,
            max_new_tokens=args.max_new_tokens,
            problem_idx=args.problem_idx,
            gpu_memory_utilization=args.gpu_mem,
            tensor_parallel_size=args.tp,
        )
        all_entropies["student2"] = (ent, pl, tl)

    # --- Combined comparison plot (response only) ---
    if len(all_entropies) == 3:
        print("\nGenerating combined comparison plot (response only) …")
        fig, ax = plt.subplots(figsize=(16, 6))
        window = 64
        kernel = np.ones(window) / window
        palette = {"teacher": "red", "student": "green", "student2": "blue"}

        max_len = 0
        for label, (ent, pl, tl) in all_entropies.items():
            n = len(ent)
            if n == 0:
                continue
            max_len = max(max_len, n)
            positions = np.arange(n)
            smoothed = np.convolve(ent, kernel, mode="same") if n > window else ent
            ax.plot(positions, smoothed, linewidth=1.2, color=palette[label],
                    label=f"{NAME[label]} gen (mean={np.mean(ent):.2f})")


        ax.set_xlabel("Response token position", fontweight="bold")
        ax.set_ylabel("Entropy", fontweight="bold")
        ax.set_title(f"Teacher Entropy Comparison", fontweight="bold")
        ax.legend(loc="upper right", fontsize=8)
        ax.set_xlim(0, max_len)
        fig.tight_layout()
        cmp_path_png = out_dir / f"entropy_comparison_prob{args.problem_idx}.png"
        cmp_path_pdf = out_dir / f"entropy_comparison_prob{args.problem_idx}.pdf"
        fig.savefig(str(cmp_path_png), dpi=150)
        fig.savefig(str(cmp_path_pdf), dpi=150)

        plt.close(fig) 

    print("\nDone.")


if __name__ == "__main__":
    main()
